services:
  mysql_database_dev:
    image: mysql:latest
    container_name: photographer_mysql_database

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photostudio

    ports: 
      - "3310:3306"

    volumes:
      - mysql_volume:/var/lib/mysql

  mysql_database_test:
    image: mysql:latest
    container_name: photographer_mysql_database_test

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photostudio_test

    ports:
      - "3311:3306"

    volumes:
      - mysql_volume_test:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis_database
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    command: redis-server --appendonly yes

volumes:
  mysql_volume:
    driver: local
  mysql_volume_test:
    driver: local
  redis_volume:
    driver: local